name: docker

on:
  push:
  pull_request:

env:
  PLATFORM: linux/amd64
  DOCKER_CACHE_TAG: _cache
  DOCKER_REPO: renovate/renovate
  CACHE_VERSION: v2

jobs:
  build:
    runs-on: ubuntu-latest

    timeout-minutes: 20

    strategy:
      fail-fast: false
      matrix:
        target:
          [
            ghcr_inline,
            ghcr_inline-max,
            ghcr_reg,
            ghcr_reg-max,
            ghcr_no-cache,
            pkg_no-cache,
            pkg_inline,
            pkg_inline-max,
          ]

    steps:
      - name: Setup
        run: |
          set -ex
          docker buildx create --name builder --use --driver docker-container
          docker buildx inspect --bootstrap
          docker info

      - uses: actions/checkout@v2

      - name: Log into registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login docker.pkg.github.com -u ${{ github.actor }} --password-stdin
          echo "${{ secrets.GH_PACKAGES }}" | docker login ghcr.io -u viceice --password-stdin

      - name: Build the Docker images
        env:
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.repository }}
        run: |
          docker buildx bake -f test.hcl ${{matrix.target}}
          docker buildx bake -f test.hcl --set *.output=type=docker --set *.cache-to=type=inline ${{matrix.target}}

      - run: docker image ls
